apiVersion: v1
data:
  myapp.conf: "server { \n    listen 80; \n    server_name myapp.com; \n    location
    / { \n        proxy_pass http://localhost:8080; \n        add_header X-Config-Source
    \"Kubernetes-ConfigMap\"; \n    } \n}  \n"
kind: ConfigMap
metadata:
  name: myapp-conf