apiVersion: v1
kind: Pod
metadata:
  name: pod-with-sidecar
  labels:
    app: nginx
spec:
  containers:
  - name: web-server
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html-content
      mountPath: /usr/share/nginx/html

  - name: content-sync
    image: busybox
    command: ["sh", "-c"]
    args:
    - |
      while true; do
        echo "<html><body><h1>Hello from the sidecar container at $(date)</h1></body></html>" > /data/index.html
        echo "Sidecar: updated /data/index.html"
        sleep 10
      done
    volumeMounts:
    - name: html-content
      mountPath: /data
  volumes:
  - name: html-content
    emptyDir: {}

