apiVersion: v1
kind: Pod
metadata:
  name: pod-with-nfs-volume
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nfs-vol
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nfs-vol
    nfs:
      server: 10.10.10.11
      path: /mnt/nfs_share
      ReadOnly: false
      