apiVersion: v1 
kind: Pod 
metadata: 
  name: wp-secret-volume-pod 
spec: 
  containers: 
  - name: wordpress 
    image: wordpress 
    env:     
    - name: WORDPRESS_DB_USER 
      valueFrom: 
        secretKeyRef: 
          name: wp-secret 
          key: username 
    - name: WORDPRESS_DB_PASSWORD 
      valueFrom: 
        secretKeyRef: 
          name: wp-secret 
          key: password 
    volumeMounts: 
    - name: secrets-volume 
      mountPath: "/etc/ssl/certs/wordpress" 
      readOnly: true 
  volumes: 
  - name: secrets-volume 
    secret: 
      secretName: wp-tls-secret 