apiVersion: v1
kind: Pod
metadata:
  name: emptydir-multi-container-pod
  labels:
    app: web
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/nginx
    - name: busybox-container
      image: busybox:latest
      command:
        - "sleep"
        - "3600"
      volumeMounts:
        - name: shared-logs
          mountPath: /shared/logs
  volumes:
    - name: shared-logs
      emptyDir: {}
